import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: ".",
	entryNames: "main",
	assetNames: "styles",
	chunkNames: "[name]-[hash]",
	minify: prod,
	loader: {
		".css": "css",
	},
	plugins: [
		{
			name: "rename-css",
			setup(build) {
				build.onEnd(async () => {
					const fs = await import("fs");
					const mainCss = "main.css";
					const stylesCss = "styles.css";

					if (fs.existsSync(mainCss)) {
						// Read the CSS file and remove sourcemap comment
						let cssContent = fs.readFileSync(mainCss, "utf-8");
						// Remove inline sourcemap (last line starting with /*# sourceMappingURL=)
						cssContent = cssContent.replace(
							/\/\*#\s*sourceMappingURL=.*\*\/\s*$/,
							"",
						);

						// Write to styles.css
						fs.writeFileSync(stylesCss, cssContent);
						fs.unlinkSync(mainCss);
						console.log(
							"Renamed main.css to styles.css and removed sourcemap",
						);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
